import type { IncidentDoc } from '../../types.js'
import { DAY_MS } from './dates.js'

export function extraIncidentsA(): IncidentDoc[] {
  const now = Date.now()
  return [
    {
      alarm_name: 'ElastiCache-MemoryPressure',
      description: 'Redis evicting keys under memory pressure.',
      state: 'resolved',
      severity: 'medium',
      category: 'memory',
      timestamp: new Date(now - 3 * DAY_MS).toISOString(),
      resolved_at: new Date(now - 3 * DAY_MS + 35 * 60 * 1000).toISOString(),
      metric_name: 'CurrConnections',
      namespace: 'AWS/ElastiCache',
      service: 'session-cache',
      dimensions: { CacheClusterId: 'session-cache' },
      root_cause: 'Memory eviction policy too aggressive for workload.',
      resolution: 'Switched to allkeys-lru and scaled node type.',
      resolution_time_minutes: 35,
      auto_resolved: false,
      tags: ['redis', 'memory', 'eviction'],
    },
    {
      alarm_name: 'ALB-5xx-High',
      description: 'ALB 5xx spike after deployment.',
      state: 'resolved',
      severity: 'critical',
      category: 'errors',
      timestamp: new Date(now - 4 * DAY_MS).toISOString(),
      resolved_at: new Date(now - 4 * DAY_MS + 20 * 60 * 1000).toISOString(),
      metric_name: 'HTTPCode_ELB_5XX_Count',
      namespace: 'AWS/ApplicationELB',
      service: 'app/web',
      dimensions: { LoadBalancer: 'app/web-prod' },
      root_cause: 'Missing environment variable in deployment manifest.',
      resolution: 'Restored env var; redeployed.',
      resolution_time_minutes: 20,
      auto_resolved: false,
      tags: ['5xx', 'deployment', 'config'],
    },
    {
      alarm_name: 'ALB-5xx-High',
      description: 'ALB 5xx from image processing service.',
      state: 'resolved',
      severity: 'high',
      category: 'errors',
      timestamp: new Date(now - 8 * DAY_MS).toISOString(),
      resolved_at: new Date(now - 8 * DAY_MS + 45 * 60 * 1000).toISOString(),
      metric_name: 'HTTPCode_ELB_5XX_Count',
      namespace: 'AWS/ApplicationELB',
      service: 'app/images',
      dimensions: { LoadBalancer: 'app/images' },
      root_cause: 'Memory leak in image processing workers.',
      resolution: 'Restarted tasks; deployed fix for buffer handling.',
      resolution_time_minutes: 45,
      auto_resolved: false,
      tags: ['5xx', 'memory-leak', 'images'],
    },
    {
      alarm_name: 'EC2-DiskSpace-Low',
      description: 'Low disk space on bastion host.',
      state: 'resolved',
      severity: 'medium',
      category: 'disk',
      timestamp: new Date(now - 12 * DAY_MS).toISOString(),
      resolved_at: new Date(now - 12 * DAY_MS + 55 * 60 * 1000).toISOString(),
      metric_name: 'disk_used_percent',
      namespace: 'CWAgent',
      service: 'bastion',
      dimensions: { InstanceId: 'i-bastion' },
      root_cause: 'Log rotation not configured for application logs.',
      resolution: 'Enabled logrotate and retention.',
      resolution_time_minutes: 55,
      auto_resolved: false,
      tags: ['disk', 'bastion', 'logs'],
    },
    {
      alarm_name: 'ACM-Cert-Expiry',
      description: 'ACM certificate renewal failing.',
      state: 'resolved',
      severity: 'high',
      category: 'other',
      timestamp: new Date(now - 18 * DAY_MS).toISOString(),
      resolved_at: new Date(now - 18 * DAY_MS + 40 * 60 * 1000).toISOString(),
      metric_name: 'DaysToExpiry',
      namespace: 'AWS/CertificateManager',
      service: 'shop.example.com',
      dimensions: { CertificateArn: 'arn:aws:acm:ap-southeast-1:123:certificate/abc' },
      root_cause: 'DNS validation record deleted during DNS cleanup.',
      resolution: 'Restored CNAME; reissued certificate.',
      resolution_time_minutes: 40,
      auto_resolved: false,
      tags: ['ssl', 'acm', 'dns'],
    },
  ]
}
