import type { IncidentDoc } from '../../types.js'
import { DAY_MS } from './dates.js'

export function extraIncidentsB(): IncidentDoc[] {
  const now = Date.now()
  return [
    {
      alarm_name: 'ECS-TaskStartFailed',
      description: 'ECS tasks failing to pull image.',
      state: 'resolved',
      severity: 'high',
      category: 'other',
      timestamp: new Date(now - 9 * DAY_MS).toISOString(),
      resolved_at: new Date(now - 9 * DAY_MS + 30 * 60 * 1000).toISOString(),
      metric_name: 'RunningTaskCount',
      namespace: 'AWS/ECS',
      service: 'checkout',
      dimensions: { ServiceName: 'checkout', ClusterName: 'prod-cluster' },
      root_cause: 'ECR lifecycle policy deleted referenced image tag.',
      resolution: 'Pinned digest; adjusted lifecycle rules.',
      resolution_time_minutes: 30,
      auto_resolved: false,
      tags: ['ecs', 'ecr', 'lifecycle'],
    },
    {
      alarm_name: 'Lambda-Throttles',
      description: 'Lambda throttles during flash sale.',
      state: 'resolved',
      severity: 'medium',
      category: 'serverless',
      timestamp: new Date(now - 2 * DAY_MS).toISOString(),
      resolved_at: new Date(now - 2 * DAY_MS + 15 * 60 * 1000).toISOString(),
      metric_name: 'Throttles',
      namespace: 'AWS/Lambda',
      service: 'pricing',
      dimensions: { FunctionName: 'pricing' },
      root_cause: 'Concurrency limit too low for flash sale traffic.',
      resolution: 'Raised reserved concurrency for event window.',
      resolution_time_minutes: 15,
      auto_resolved: false,
      tags: ['lambda', 'throttle', 'sale'],
    },
    {
      alarm_name: 'SQS-DLQ-Depth',
      description: 'DLQ depth growing for payment queue.',
      state: 'resolved',
      severity: 'high',
      category: 'other',
      timestamp: new Date(now - 14 * DAY_MS).toISOString(),
      resolved_at: new Date(now - 14 * DAY_MS + 70 * 60 * 1000).toISOString(),
      metric_name: 'ApproximateNumberOfMessagesVisible',
      namespace: 'AWS/SQS',
      service: 'payments-dlq',
      dimensions: { QueueName: 'payments-dlq' },
      root_cause: 'Payment provider changed API format without notice.',
      resolution: 'Updated consumer schema; replayed DLQ.',
      resolution_time_minutes: 70,
      auto_resolved: false,
      tags: ['sqs', 'dlq', 'provider'],
    },
    {
      alarm_name: 'NatGateway-BytesOut',
      description: 'NAT gateway data transfer spike.',
      state: 'resolved',
      severity: 'medium',
      category: 'other',
      timestamp: new Date(now - 20 * DAY_MS).toISOString(),
      resolved_at: new Date(now - 20 * DAY_MS + 25 * 60 * 1000).toISOString(),
      metric_name: 'BytesOutToDestination',
      namespace: 'AWS/NATGateway',
      service: 'nat-0',
      dimensions: { NatGatewayId: 'nat-0abc' },
      root_cause: 'Cron job running every minute instead of hourly.',
      resolution: 'Fixed schedule; moved heavy pulls to S3 VPC endpoint.',
      resolution_time_minutes: 25,
      auto_resolved: false,
      tags: ['nat', 'cron', 'cost'],
    },
  ]
}
